-- Seed: categories + products (generated from data.js)

insert into public.categories (id,name_en,name_es,sort) values
  ('chemical','Car Wash Soaps','Jabones de lavado',0),
  ('tunnel','Express Tunnel','Túnel exprés',1),
  ('finishing','Finishing Touches','Toques finales',2),
  ('waxes','Waxes & Compounds','Ceras y compuestos',3),
  ('brands','3M · P&S · Malco','3M · P&S · Malco',4),
  ('supplies','Supplies & Equipment','Suministros y equipo',5)
on conflict (id) do update set name_en=excluded.name_en, name_es=excluded.name_es, sort=excluded.sort;

insert into public.products (slug,category_id,brand,name_en,name_es,desc_en,desc_es,sizes,sds,tag,sort_order,active) values
  ('blue-soap','chemical','Golden West','Blue Carwash Soap','Jabón Azul para Autos','High-pH, high-foaming formula for mechanical or hand washing. Spotless, streak-free shine in hard or soft water.','Fórmula de pH alto y alta espuma para lavado mecánico o a mano. Brillo impecable sin manchas en agua dura o blanda.',ARRAY['5 gal','15 gal','30 gal','55 gal drum']::text[],true,'High pH',0,true),
  ('maxi-foam','chemical','Golden West','Maxi-Foam Carwash Soap','Jabón Maxi-Foam','Rich, clinging foam for mechanical or hand operations. Excellent in hard or soft water with no streaking or water spotting.','Espuma rica y adherente para operaciones mecánicas o a mano. Excelente en agua dura o blanda, sin rayas ni manchas.',ARRAY['5 gal','15 gal','55 gal drum']::text[],true,'Best seller',1,true),
  ('pink-soap','chemical','Golden West','Pink Carwash Soap','Jabón Rosa para Autos','Versatile high-foaming soap that works brilliantly in any water. Leaves vehicles spotless and streak-free.','Jabón versátil de alta espuma que funciona en cualquier agua. Deja los vehículos impecables y sin rayas.',ARRAY['5 gal','15 gal','30 gal','55 gal drum']::text[],true,NULL,2,true),
  ('wash-wax','chemical','Golden West','Purple & Pink Wash + Wax','Lavado + Cera Púrpura y Rosa','Premium high-foam soap with wax protection in one step. Cleans, shines and beads water in a single pass.','Jabón premium de alta espuma con protección de cera en un solo paso. Limpia, da brillo y repele el agua.',ARRAY['5 gal','15 gal','55 gal drum']::text[],true,'2-in-1',3,true),
  ('touchless','chemical','Golden West','Touchless Soap (Concentrated)','Jabón Sin Contacto (Concentrado)','Biodegradable, highly concentrated touch-free detergent for automatic and touchless systems. A little goes a long way.','Detergente sin contacto altamente concentrado y biodegradable para sistemas automáticos. Rinde muchísimo.',ARRAY['5 gal','30 gal','55 gal drum','275 gal tote']::text[],true,'Concentrated',4,true),
  ('presoak','tunnel','Golden West','Tunnel Presoak / Prep','Prelavado para Túnel','Heavy-duty presoak that breaks down road film and bug residue before the wash. Tuned for high-throughput tunnels.','Prelavado de alto rendimiento que disuelve la película de carretera y residuos de insectos antes del lavado. Ideal para túneles de alto volumen.',ARRAY['30 gal','55 gal drum','275 gal tote']::text[],true,NULL,5,true),
  ('foam-conditioner','tunnel','Golden West','Foam Conditioner (Triple Color)','Acondicionador de Espuma (Tricolor)','Thick, fragrant triple-color foam conditioner that lubricates the wash and gives tunnels that signature curtain look.','Acondicionador de espuma tricolor espeso y aromático que lubrica el lavado y da a los túneles ese look de cortina característico.',ARRAY['5 gal','55 gal drum']::text[],true,NULL,6,true),
  ('drying-agent','tunnel','Golden West','Drying Agent / Sheeting Wax','Agente de Secado / Cera de Escurrido','Sheeting drying agent that pushes water off the vehicle for fast, spot-free drying at tunnel speed.','Agente de secado que desplaza el agua del vehículo para un secado rápido y sin manchas a velocidad de túnel.',ARRAY['5 gal','55 gal drum']::text[],true,NULL,7,true),
  ('trim-shine','finishing','Golden West','Stone Trim Shine Ceramic','Cerámico Stone Trim Shine','Hard ceramic trim coating that restores deep shine to dull plastic, vinyl and painted trim — acts like a clearcoat.','Recubrimiento cerámico duro que restaura el brillo profundo en molduras de plástico, vinilo y pintadas — actúa como transparente.',ARRAY['Kit','1 gal']::text[],true,'Ceramic',8,true),
  ('tire-shine','finishing','Golden West','Tire Shine Dressing','Abrillantador de Llantas','Long-lasting tire and trim dressing with a rich wet look. Sprays on evenly and resists sling.','Abrillantador duradero para llantas y molduras con un look mojado intenso. Se aplica uniforme y resiste el salpicado.',ARRAY['1 gal','5 gal']::text[],true,NULL,9,true),
  ('glass-cleaner','finishing','Golden West','Streak-Free Glass Cleaner','Limpiavidrios Sin Rayas','Ammonia-free glass cleaner that wipes clear with no haze or streaks. Safe on tint.','Limpiavidrios sin amoníaco que seca claro sin neblina ni rayas. Seguro sobre polarizado.',ARRAY['1 gal','5 gal']::text[],true,NULL,10,true),
  ('cherry-flash','waxes','Malco','Malco Cherry Flash Wax','Cera Malco Cherry Flash','Popular liquefied carnauba paste wax. Applies easily, dries fast and leaves a deep, long-lasting shine.','Popular cera de pasta de carnauba licuada. Se aplica fácil, seca rápido y deja un brillo profundo y duradero.',ARRAY['Quart','1 gal']::text[],true,NULL,11,true),
  ('hd-compound','waxes','EPIC','Heavy Duty Compound','Compuesto de Alto Rendimiento','Cutting compound that removes P1500 sand scratches and oxidation, then polishes to gloss in one step.','Compuesto de corte que elimina rayas de lija P1500 y oxidación, y pule a brillo en un solo paso.',ARRAY['Quart','1 gal']::text[],true,NULL,12,true),
  ('3m-rubbing','brands','3M','3M Rubbing Compound, 32 oz','Compuesto Pulidor 3M, 32 oz','Fine-abrasive compound that removes defects and restores paint to its original luster.','Compuesto de abrasivo fino que elimina defectos y restaura el brillo original de la pintura.',ARRAY['32 oz']::text[],true,NULL,13,true),
  ('3m-polish','brands','3M','3M Perfect-It EX Machine Polish','Pulidor de Máquina 3M Perfect-It EX','3M''s highest-performing machine polish for removing swirl marks. Stays wet longer, uses less product.','El pulidor de máquina de mayor rendimiento de 3M para eliminar marcas de remolino. Se mantiene húmedo más tiempo y usa menos producto.',ARRAY['Quart']::text[],true,NULL,14,true),
  ('ps-detail','brands','P&S','P&S Interior & Detail Line','Línea Interior y Detallado P&S','Professional P&S interior cleaners, dressings and detail sprays. Ask us for the full P&S, Malco and Stoner catalog.','Limpiadores, acondicionadores y aerosoles de detallado profesional P&S. Pregúntanos por el catálogo completo P&S, Malco y Stoner.',ARRAY['Various']::text[],true,NULL,15,true),
  ('truck-brush','supplies','Golden West','Soft Nylon Truck Brush','Cepillo de Nylon para Camiones','Durable, heavy-duty flow-through brush with soft nylon bristles. Won''t scratch, built to last.','Cepillo resistente de flujo con cerdas de nylon suave. No raya y está hecho para durar.',ARRAY['Single','Case']::text[],false,NULL,16,true),
  ('air-hose','supplies','Golden West','Air & Water Hoses','Mangueras de Aire y Agua','Coiled and straight air/water hoses, triggers and bottles. Buy more, save more.','Mangueras de aire/agua rectas y en espiral, gatillos y botellas. Compra más, ahorra más.',ARRAY['25 ft','50 ft','Case']::text[],false,NULL,17,true),
  ('towels','supplies','Golden West','Microfiber Towels (Bulk)','Toallas de Microfibra (a Granel)','Professional microfiber towels by the dozen or case. Lint-free, machine-washable, high-GSM.','Toallas de microfibra profesionales por docena o caja. Sin pelusa, lavables a máquina, alto GSM.',ARRAY['Dozen','Case']::text[],false,NULL,18,true),
  ('spray-bottles','supplies','Golden West','Bottles, Triggers & Foamers','Botellas, Gatillos y Espumadores','Chemical-resistant spray bottles, trigger sprayers and foaming heads sized for detail shops and tunnels.','Botellas resistentes a químicos, gatillos y cabezales espumadores para talleres de detallado y túneles.',ARRAY['Each','Case']::text[],false,NULL,19,true)
on conflict (slug) do nothing;
